INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('1', '1', 'ounce' ); -- 'Beef (Beef Herd) DIVIDE BY 16.67'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('2', '1', 'ounce' ); -- 'Lamb & Mutton DIVIDE BY 16.67'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('3', '1', 'ounce') -- 'Beef (Dairy Herd) DIVIDE BY 16.67'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('4', '1', 'ounce'); -- 'Crustaceans (farmed) DIVIDE BY 20'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('5', '1', 'ounce'); -- 'Cheese DIVIDE BY 25'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('6', '1', 'ounce'); -- 'Pig Meat DIVIDE BY 16.67'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('7', '1', 'ounce'); -- 'Fish (farmed) DIVIDE BY 16.67'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('8', '1', 'ounce'); -- 'Poultry Meat DIVIDE BY 16.67'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('9', '1', 'Egg'); -- 'Eggs DIVIDE BY 16.67'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('10', '1', 'cup'); -- 'Tofu DIVIDE BY 4'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('11', '1', 'ounce'); -- 'Groundnuts DIVIDE BY 14.3
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('12', '1', 'cup'); -- 'Beans, Potatoes, Lentils DIVIDE BY 14.3
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('13', '100', 'grams'); -- 'Peas DIVIDE BY 16.67'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('14', '100', 'grams'); -- 'Nuts DIVIDE BY 5'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('15', '1', 'cup'); -- 'Grains DIVIDE BY 33'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('16', '1', 'liter'); -- 'Milk'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('17', '1', 'liter'); -- 'Soy Milk'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('18', '1', 'cup'); -- 'Cassava DIVIDE BY 6.25 in env data'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('19', '100', 'grams'); -- 'Rice (flooded) DIVIDE BY 6.6 in env data'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('20', '1', 'cup' ); -- 'Oatmeal DIVIDE BY 3.33'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('21', '100', 'grams' ); -- 'Potatoes DIVIDE BY 17.24'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('22', '100', 'grams'); -- 'Wheat and Rye Bread DIVIDE BY 3.8'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('23', '100', 'grams'); -- 'Maize (Meal) DIVIDE BY 9.9'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('24', '1', 'tbsp'); -- 'Palm Oil   OILS DIVIDE BY 67.628'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('25', '1', 'tbsp'); -- 'Soybean Oil'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('26', '1', 'tbsp'); -- 'Olive Oil'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('27', '1', 'tbsp'); -- 'Rapeseed Oil'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('28', '1', 'tbsp'); -- 'Sunflower Oil'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('29', '1', 'tomato'); -- 'Tomatoes DIVIDE BY 8'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('30', '100', 'grams'); -- 'Brassicas DIVIDE BY 10'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('31', '100', 'grams'); -- 'Onions & Leeks DIVIDE BY 10'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('32', '100', 'grams'); -- 'Root Vegetables DIVIDE BY 10'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('33', '100', 'grams'); -- 'Berries DIVIDE BY 10'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('34', '100', 'grams'); -- 'Bananas DIVIDE BY 10'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('35', '100', 'grams'); -- 'Apples DIVIDE BY 10'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('36', '100', 'grams'); -- 'Citrus DIVIDE BY 10'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('37', '1', 'tsp'); -- 'Cane Sugar DIVIDE BY 203'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('38', '1', 'tsp'); -- 'Beet Sugar DIVIDE BY 203'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('39', '1', 'unit'); -- 'Beer (5% ABV)'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('40', '1', 'unit'); -- 'Wine (12.5% ABV)'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('41', '50', 'grams' ); -- 'Dark Chocolate (50g)'
INSERT INTO `food_weights` (`FOOD_ID`, `WEIGHT`, `UOM`) VALUES ('42', '1', 'cup' ); -- 'Coffee (15g, 1 cup)'