INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('1', '16.67'; -- 'Beef (Beef Herd) DIVIDE BY 16.67'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('2', '16.67'); -- 'Lamb & Mutton DIVIDE BY 16.67'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('3', '16.67') -- 'Beef (Dairy Herd) DIVIDE BY 16.67'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('4', '20'); -- 'Crustaceans (farmed) DIVIDE BY 20'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('5', '25'); -- 'Cheese DIVIDE BY 25'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('6', '16.67'); -- 'Pig Meat DIVIDE BY 16.67'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('7', '16.67'); -- 'Fish (farmed) DIVIDE BY 16.67'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('8', '16.67'); -- 'Poultry Meat DIVIDE BY 16.67'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('9', '16.67'); -- 'Eggs DIVIDE BY 16.67'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('10', '4'); -- 'Tofu DIVIDE BY 4'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('11', '14.3'); -- 'Groundnuts DIVIDE BY 14.3
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('12', '14.3'); -- 'Beans, Potatoes, Lentils DIVIDE BY 14.3
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('13', '16.67'); -- 'Peas DIVIDE BY 16.67'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('14', '5'); -- 'Nuts DIVIDE BY 5'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('15', '33'); -- 'Grains DIVIDE BY 33'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('16', '1'); -- 'Milk'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('17', '1'); -- 'Soy Milk'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('18', '6.25'); -- 'Cassava DIVIDE BY 6.25 in env data'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('19', '6.6'); -- 'Rice (flooded) DIVIDE BY 6.6 in env data'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('20', '3.33' ); -- 'Oatmeal DIVIDE BY 3.33'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('21', '17.24' ); -- 'Potatoes DIVIDE BY 17.24'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('22', '3.8'); -- 'Wheat and Rye Bread DIVIDE BY 3.8'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('23', '9.9'); -- 'Maize (Meal) DIVIDE BY 9.9'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('24', '67.628'); -- 'Palm Oil   OILS DIVIDE BY 67.628'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('25', '67.628'); -- 'Soybean Oil'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('26', '67.628'); -- 'Olive Oil'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('27', '67.628'); -- 'Rapeseed Oil'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('28', '67.628'); -- 'Sunflower Oil'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('29', '8'); -- 'Tomatoes DIVIDE BY 8'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('30', '10'); -- 'Brassicas DIVIDE BY 10'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('31', '10'); -- 'Onions & Leeks DIVIDE BY 10'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('32', '10'); -- 'Root Vegetables DIVIDE BY 10'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('33', '10'); -- 'Berries DIVIDE BY 10'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('34', '10'); -- 'Bananas DIVIDE BY 10'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('35', '10'); -- 'Apples DIVIDE BY 10'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('36', '10'); -- 'Citrus DIVIDE BY 10'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('37', '203'); -- 'Cane Sugar DIVIDE BY 203'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('38', '203'); -- 'Beet Sugar DIVIDE BY 203'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('39', '1'); -- 'Beer (5% ABV)'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('40', '1'); -- 'Wine (12.5% ABV)'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('41', '1' ); -- 'Dark Chocolate (50g)'
INSERT INTO `food_normalization` (`FOOD_ID`, `DIVIDE_BY`) VALUES ('42', '1'); -- 'Coffee (15g, 1 cup)'