INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('1', '50', '164', '50-150+', '60-150+', '0-50'); -- 'Beef (Beef Herd) DIVIDE BY 16.67'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('2', '20', '185', '50-75', '0-60', '0-100+'); -- 'Lamb & Mutton DIVIDE BY 16.67'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('3', '17', '22', '100-150+', '50-150+', '25-90'); -- 'Beef (Dairy Herd) DIVIDE BY 16.67'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('4', '18', '2', '50-150+', '50-150+', '20-90'); -- 'Crustaceans (farmed) DIVIDE BY 20'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('5', '11', '41', '20-115', '10-75', '0-100+'); -- 'Cheese DIVIDE BY 25'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('6', '7.6', '11', '40-150+', '10-135', '0-75'); -- 'Pig Meat DIVIDE BY 16.67'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('7', '6', '3.7', '10-25', '20-150+', '5-50'); -- 'Fish (farmed) DIVIDE BY 16.67'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('8', '5.7', '7.1', '15-90', '10-50', '0-25'); -- 'Poultry Meat DIVIDE BY 16.67'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('9', '4.2', '5.7', '10-65', '0-5', '0-35'); -- 'Eggs DIVIDE BY 16.67'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('10', '2', '2.2', '1', '1', '0-20'); -- 'Tofu DIVIDE BY 4'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('11', '1.2', '3.5', '0-10', '1', '0-75'); -- 'Groundnuts DIVIDE BY 14.3
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('12', '0.8', '7.3', '0-7', '0-10', '0-20'); -- 'Beans, Potatoes, Lentils DIVIDE BY 14.3
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('13', '0.4', '3.4', '1', '0-5', '0-100'); -- 'Peas DIVIDE BY 16.67'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('14', '0.3', '7.9', '10-50', '0-15', '0-100+'); -- 'Nuts DIVIDE BY 5'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('15', '2.7', '4.6', '0-15', '0-30', '0-60'); -- 'Grains DIVIDE BY 33'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('16', '3.2', '8.9', '10-30+', '3-19', '0-75'); -- 'Milk'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('17', '1', '0.7', '2', '1', '0-5'); -- 'Soy Milk'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('18', '1.4', '1.9', '4-5', '1', '0'); -- 'Cassava DIVIDE BY 6.25 in env data'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('19', '1.2', '0.8', '3-10+', '1-10+', '0-30'); -- 'Rice (flooded) DIVIDE BY 6.6 in env data'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('20', '0.9', '2.9', '3-5', '3-6', '0-10' ); -- 'Oatmeal DIVIDE BY 3.33'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('21', '0.6', '1.2', '3-7', '1-9', '0-10' ); -- 'Potatoes DIVIDE BY 17.24'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('22', '0.6', '1.4', '3-7', '1-5', '0-20'); -- 'Wheat and Rye Bread DIVIDE BY 3.8'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('23', '0.4', '0.7', '1-5', '0-2', '0-5'); -- 'Maize (Meal) DIVIDE BY 9.9'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('24', '7.3', '2.4', '20-25', '5-15', '0'); -- 'Palm Oil   OILS DIVIDE BY 67.628'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('25', '6.3', '11', '10-20', '0-20', '0-75'); -- 'Soybean Oil'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('26', '5.4', '26', '25-50', '15-55', '0-100+'); -- 'Olive Oil'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('27', '3.8', '11', '10-45', '5-35', '0-20'); -- 'Rapeseed Oil'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('28', '3.6', '18', '10-55', '10-60+', '0-150'); -- 'Sunflower Oil'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('29', '2.1', '0.8', '3-20+', '1-20+', '10-40'); -- 'Tomatoes DIVIDE BY 8'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('30', '0.5', '0.6', '4-10', '2-7', '0-20'); -- 'Brassicas DIVIDE BY 10'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('31', '0.5', '0.4', '3-4', '2-7', '0-5'); -- 'Onions & Leeks DIVIDE BY 10'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('32', '0.4', '0.3', '3', '0-2', '0-6'); -- 'Root Vegetables DIVIDE BY 10'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('33', '1.5', '2.4', '5-20+', '1-17', '10-40'); -- 'Berries DIVIDE BY 10'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('34', '0.9', '1.9', '5-8', '3-6', '1'); -- 'Bananas DIVIDE BY 10'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('35', '0.4', '0.6', '2-3', '0-2', '0-50'); -- 'Apples DIVIDE BY 10'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('36', '0.4', '0.9', '2-4', '0-5', '0-15'); -- 'Citrus DIVIDE BY 10'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('37', '3.2', '2.0', '10-25', '5-40', '0-35'); -- 'Cane Sugar DIVIDE BY 203'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('38', '1.8', '1.8', '3-18', '1-12', '0-25'); -- 'Beet Sugar DIVIDE BY 203'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('39', '0.24', '0.22', '1.1-1.4', '0.25-0.75', '0-0.05'); -- 'Beer (5% ABV)'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('40', '0.14', '0.14', '0.75-1.8', '0.25-0.75', '0-0.13'); -- 'Wine (12.5% ABV)'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('41', '2.3', '3.4', '1-6', '0-11', '0-0.8' ); -- 'Dark Chocolate (50g)'
INSERT INTO `food_impact` (`FOOD_ID`, `GHG`, `LAND_USE`, `ACID`, `EUTROPH`, `SCARCITY_WATER`) VALUES ('42', '0.4', '0.3', '1-2', '0-3', '0-0.01'); -- 'Coffee (15g, 1 cup)'